server:
#  error:
#    include-message: always
#    include-binding-errors: always
  port: 8080
  servlet:
    context-path: /all-info

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?useEncoding=true&characterEncoding-UTF8
    username: postgres
    password: SERiyye09
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:dbchange/master.xml
    drop-first: false
    default-schema: public
    database-change-log-table: public.login_changelog
    database-change-log-lock-table: public.login_changelog_lock

  mail:
    host: smtp.gmail.com
    port: 587
    username: gultekin398@gmail.com
    password: rbiomzytpnlchzgl

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  web:
    resources:
      add-mappings: true

jwt:
  header: Authorization
  prefix: Bearer
  expiration: 80000
  secretKey: 65hgfhDFSF!@!@33wdq3r3tsdGsf22VXv343&3l071&65hgfhDFSF!@!@33wdq3r3tsdGsf22VXv343&3l071&